name: App Distributor Reminder

on:
  schedule:
    - cron: "36 * * * *"

jobs:
  remind:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: run slack reminder
        run: |
          chmod +x ./gradle/scripts/actions/distributor_reminder.sh
            ./gradle/scripts/actions/distributor_reminder.sh ${{ secrets.SLACK_WEBHOOK_URL }}
      
      - name: commit changes
        run: |
          git config --global user.name "DanDanyKim"
          git config --global user.email "danhee.kim@birdview.kr"

          currentBranch=$(git branch --show-current)
          git pull origin ${currentBranch}
          
          git add -A
          git commit -m "update distributor sequence"
          git push
