name: App Distributor Reminder

on: push

env:
  DISTRIBUTORS: |
    (
      "김다슬", 
      "김단희"
    )
  DISTRIBUTOR_SEQUENCE: ${{ vars.DISTRIBUTOR_SEQUENCE }}

jobs:
  remind:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Slack
        uses: rtCamp/action-slack-notify@v2.2.0
        env:
          SLACK_USERNAME: 안드로이드 배포 담당자 알리미
          SLACK_TITLE: 안드로이드 배포 담당자 알리미
          SLACK_MESSAGE: 이번 배포 담당자는 $DISTRIBUTOR_SEQUENCE 님 입니다
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
      - name: Update Sequence
        run: |
          echo "DISTRIBUTOR_SEQUENCE=${{ DISTRIBUTOR_SEQUENCE + 1 }}" >> $GITHUB_ENV
