name: Work Schedule Alarmy

on: push

jobs:
  alarmy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install axios

      - name: run work schedule alarmy
        run: |
          chmod +x ./gradle/scripts/actions/work_schedule_alarmy.js
           node ./gradle/scripts/actions/work_schedule_alarmy.js ${{ vars.FLEX_EMAIL }} ${{ secrets.FLEX_PASSWORD }} ${{ vars.FLEX_ANDROID_DEPARTMENT_ID }} ${{ secrets.SLACK_WORK_SCHEDULE_WEBHOOK_URL }}
